game_record = {
  replay_speed: 8,
  start_tiles: [{ x: 3, y: 0, val: 1 }, { x: 3, y: 1, val: 1 }, ],
  moves: [
      { direction: 1,
        new_tile: { x: 3, y: 3, val: 1 } },
      { direction: 0,
        new_tile: { x: 2, y: 2, val: 1 } },
      { direction: 1,
        new_tile: { x: 0, y: 3, val: 1 } },
      { direction: 0,
        new_tile: { x: 1, y: 1, val: 1 } },
      { direction: 1,
      new_tile: null },
      { direction: 0,
        new_tile: { x: 1, y: 1, val: 1 } },
      { direction: 1,
        new_tile: { x: 3, y: 1, val: 1 } },
      { direction: 1,
        new_tile: { x: 2, y: 0, val: 1 } },
      { direction: 0,
      new_tile: null },
      { direction: 2,
        new_tile: { x: 1, y: 1, val: 1 } },
      { direction: 3,
        new_tile: { x: 2, y: 2, val: 1 } },
      { direction: 3,
      new_tile: null },
      { direction: 2,
      new_tile: null },
      { direction: 3,
      new_tile: null },
      { direction: 3,
      new_tile: null },
      { direction: 2,
      new_tile: null },
      { direction: 3,
      new_tile: null },
      { direction: 2,
      new_tile: null },
      { direction: 3,
      new_tile: null },
      { direction: 1,
        new_tile: { x: 0, y: 0, val: 1 } },
      { direction: 0,
        new_tile: { x: 0, y: 2, val: 1 } },
      { direction: 3,
        new_tile: { x: 1, y: 1, val: 1 } },
      { direction: 0,
        new_tile: { x: 1, y: 0, val: 1 } },
      { direction: 3,
      new_tile: null },
      { direction: 0,
      new_tile: null },
      { direction: 3,
      new_tile: null },
      { direction: 0,
      new_tile: null },
      { direction: 2,
        new_tile: { x: 0, y: 2, val: 1 } },
      { direction: 1,
        new_tile: { x: 1, y: 2, val: 1 } },
      { direction: 0,
        new_tile: { x: 1, y: 2, val: 1 } },
      { direction: 0,
      new_tile: null },
      { direction: 2,
        new_tile: { x: 3, y: 3, val: 1 } },
      { direction: 1,
        new_tile: { x: 3, y: 3, val: 1 } },
      { direction: 0,
        new_tile: { x: 3, y: 2, val: 1 } },
      { direction: 3,
        new_tile: { x: 3, y: 3, val: 1 } },
      { direction: 2,
        new_tile: { x: 3, y: 0, val: 1 } },
      { direction: 2,
      new_tile: null },
      { direction: 1,
        new_tile: { x: 0, y: 3, val: 1 } },
      { direction: 0,
        new_tile: { x: 3, y: 2, val: 1 } },
      { direction: 3,
        new_tile: { x: 1, y: 0, val: 1 } },
      { direction: 2,
        new_tile: { x: 1, y: 0, val: 2 } },
      { direction: 0,
        new_tile: { x: 3, y: 3, val: 1 } },
      { direction: 2,
        new_tile: { x: 3, y: 0, val: 1 } },
      { direction: 1,
        new_tile: { x: 0, y: 1, val: 1 } },
      { direction: 0,
        new_tile: { x: 2, y: 1, val: 1 } },
      { direction: 1,
      new_tile: null },
      { direction: 3,
        new_tile: { x: 1, y: 0, val: 1 } },
      { direction: 2,
        new_tile: { x: 1, y: 0, val: 1 } },
      { direction: 0,
        new_tile: { x: 2, y: 0, val: 1 } },
      { direction: 1,
        new_tile: { x: 2, y: 1, val: 1 } },
      { direction: 2,
        new_tile: { x: 1, y: 0, val: 2 } },
      { direction: 0,
        new_tile: { x: 3, y: 3, val: 1 } },
      { direction: 0,
        new_tile: { x: 1, y: 3, val: 1 } },
      { direction: 2,
        new_tile: { x: 0, y: 3, val: 1 } },
      { direction: 1,
        new_tile: { x: 0, y: 2, val: 1 } },
      { direction: 0,
        new_tile: { x: 2, y: 3, val: 1 } },
      { direction: 3,
        new_tile: { x: 0, y: 0, val: 2 } },
      { direction: 2,
        new_tile: { x: 2, y: 1, val: 2 } },
      { direction: 0,
        new_tile: { x: 3, y: 0, val: 1 } },
      { direction: 1,
        new_tile: { x: 0, y: 2, val: 1 } },
      { direction: 0,
        new_tile: { x: 0, y: 2, val: 1 } },
      { direction: 1,
      new_tile: null },
      { direction: 2,
        new_tile: { x: 2, y: 2, val: 1 } },
      { direction: 0,
        new_tile: { x: 2, y: 1, val: 1 } },
      { direction: 3,
        new_tile: { x: 2, y: 1, val: 1 } },
      { direction: 0,
        new_tile: { x: 3, y: 0, val: 1 } },
      { direction: 2,
        new_tile: { x: 0, y: 3, val: 1 } },
      { direction: 1,
        new_tile: { x: 1, y: 1, val: 1 } },
      { direction: 0,
        new_tile: { x: 2, y: 0, val: 1 } },
      { direction: 2,
        new_tile: { x: 1, y: 3, val: 1 } },
      { direction: 1,
        new_tile: { x: 3, y: 2, val: 1 } },
      { direction: 0,
        new_tile: { x: 2, y: 0, val: 1 } },
      { direction: 3,
        new_tile: { x: 2, y: 2, val: 1 } },
      { direction: 0,
        new_tile: { x: 3, y: 2, val: 1 } },
      { direction: 2,
        new_tile: { x: 0, y: 1, val: 1 } },
      { direction: 1,
        new_tile: { x: 0, y: 2, val: 1 } },
      { direction: 0,
        new_tile: { x: 3, y: 0, val: 2 } },
      { direction: 2,
        new_tile: { x: 2, y: 3, val: 1 } },
      { direction: 3,
        new_tile: { x: 0, y: 3, val: 1 } },
      { direction: 0,
        new_tile: { x: 1, y: 0, val: 1 } },
      { direction: 3,
        new_tile: { x: 2, y: 3, val: 1 } },
      { direction: 1,
        new_tile: { x: 3, y: 3, val: 2 } },
  ]
};
